--- #YAML:1.0
name:               IODEF-DBI
version:            0.01_3
abstract:           Perl extension designed to create a simple storeage and indexing framework for XML based IODEF messages. 
author:
    - Wes Young <wes@barely3am.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Class::DBI:         ~
    DateTime:           ~
    LWP::Simple:        ~
    Net::Abuse::Utils:  ~
    OSSP::uuid:         ~
    XML::IODEF:         ~
    XML::LibXML:        ~
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
